name: "IC WASM CLI Action"
description: "Runs ic-wasm CLI inside Docker"

inputs:
  version:
    description: "`ic-wasm` release version (e.g. 0.9.8)"
    required: false
    default: latest
  wasm:
    description: "Path to the input WASM file"
    required: true
  output:
    description: "Optional path to the output WASM file"
    required: false
  command:
    description: "The `ic-wasm` command to run (e.g., `info`, `check-endpoints`)"
    required: true
  args:
    description: "Optional arguments for the `ic-wasm` command (e.g. `--hidden <path>` for `check-endpoints`)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Download ic-wasm binary
      shell: bash
      run: |
        set -euo pipefail
        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "latest" ]; then
          RELEASE_URL="https://github.com/dfinity/ic-wasm/releases/latest/download/ic-wasm-linux64"
        else
          RELEASE_URL="https://github.com/dfinity/ic-wasm/releases/download/${VERSION}/ic-wasm-linux64"
        fi
        
        echo "Downloading ic-wasm-linux64 from $RELEASE_URL"
        curl -sSL "$RELEASE_URL" -o ic-wasm-linux64
        chmod +x ic-wasm-linux64
        echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH

    - name: Run ic-wasm
      shell: bash
      run: |
        CMD="ic-wasm-linux64 ${{ inputs.wasm }}"
        if [ -n "${{ inputs.output }}" ]; then
          CMD="$CMD --output ${{ inputs.output }}"
        fi
        CMD="$CMD ${{ inputs.command }}"
        if [ -n "${{ inputs.args }}" ]; then
          CMD="$CMD --hidden ${{ inputs.args }}"
        fi
        echo "Running: $CMD"
        $CMD